-- create tables for TEACHER, PLAYGROUP and CHILD
CREATE TABLE IF NOT EXISTS TEACHER (
    id SERIAL PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    email VARCHAR(50) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS PLAYGROUP (
    id SERIAL PRIMARY KEY,
    groupName VARCHAR(50) NOT NULL,
    teacherId INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_teacher FOREIGN KEY (teacherId) REFERENCES TEACHER (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS CHILD (
    id SERIAL PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    age INT NOT NULL,
    email VARCHAR(50) NOT NULL,
    groupId INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_group FOREIGN KEY (groupId) REFERENCES PLAYGROUP (id) ON DELETE CASCADE
);