services:
  #---------------
  # PostgresSQL Database
  #---------------
  db:
    image: postgres:18.4
    container_name: PostgreSQL_DB
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER_SECRET}
      POSTGRES_PASSWORD: ${DB_PASSWORD_SECRET}
      POSTGRES_DB: ${DB_NAME_SECRET}
    ports:
      - "5432:5432"
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql
    networks:
      - kids_network

  #----------------
  # pgAdmin
  #---------------- 
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgAdminApp
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - kids_network

 #----------------
  # NiceGUI App
  #----------------
  nicegui:
    build: .     # Assumes your Dockerfile is in the same folder
    container_name: NiceGUI_App
    restart: always
    ports:
      - "80:80"  # Exposes NiceGUI to your host browser
    environment:
      - DB_HOST=db
      - DB_USER=${DB_USER_SECRET}
      - DB_PASSWORD=${DB_PASSWORD_SECRET}
      - DB_NAME=${DB_NAME_SECRET}
    volumes:
      - ./app:/app  # Optional: enables live-reloading during development
    depends_on:
      - db
    networks:
      - kids_network

#----------------
# Network
#----------------
networks:
  kids_network:
    #    driver: bridge

    #----------------
    # Volumes
    #---------------- 
volumes:
  postgres_data:
  pgadmin_data:
